apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass       # Nombre de la llave
  namespace: air-quality
type: Opaque
stringData:
  # Aquí ponemos la contraseña real. K8s la codificará internamente.
  password: root