apiVersion: 1

datasources:
  - name: MySQL-AirQuality
    type: mysql
    access: proxy
    orgId: 1
    # Uso 'mysql' porque es el nombre del servicio en docker-compose.
    # Dentro de la red de Docker, se llaman por su nombre, no por 'localhost'.
    url: mysql:3306
    user: root
    database: air_quality_db
    secureJsonData:
      password: "root"
    jsonData:
      tlsSkipVerify: true  # Importante para evitar líos de SSL en desarrollo
    isDefault: true
    editable: true